stages:
  - test
  - build
  - publish

default:
  interruptible:                   true
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure

variables:
  CI_REGISTRY:                     "docker.io/paritytech"
  GIT_STRATEGY:                    fetch
  CI_IMAGE:                        node:20-alpine
  DOCKERHUB_REPO:                  "paritytech"
  IMAGE_NAME:                      docker.io/$DOCKERHUB_REPO/polkadot-basic-notification
  DOCKERFILE:                      injected.Containerfile
  # BUILDAH_IMAGE is defined in group variables
  BUILDAH_COMMAND: "buildah --storage-driver overlay2"


.common-refs:                      &common-refs
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs

.test-refs:                        &test-refs
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs

.publish-refs:                     &publish-refs
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"                           # on commits to main branch
    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # on tags (i.e. v1.0, v2.1rc1)

.kubernetes-env:                   &kubernetes-env
  image:                           $CI_IMAGE
  tags:
    - kubernetes-parity-build

.collect-artifacts-short:          &collect-artifacts-short
  artifacts:
    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when:                          on_success
    expire_in:                     1 days
    paths:
      - ./artifacts/

# test that docker image can build

.build-only-docker-image:          &build-only-docker-image
  image:                           $BUILDAH_IMAGE
  script:
    - $BUILDAH_COMMAND build
      --format=docker
      --build-arg VCS_REF="${CI_COMMIT_SHA}"
      --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
      --build-arg PROJECT_NAME="${CI_PROJECT_NAME}"
      --tag "$IMAGE_NAME:latest"
      --file "$DOCKERFILE" .

check-linting:
  stage:                           test
  <<:                              *common-refs
  <<:                              *kubernetes-env
  script:
    - npm ci --ignore-scripts
    - npm run lint
  # TODO: currently fails, need fix
  allow_failure:                   True

build-npm:
  stage:                           build
  <<:                              *collect-artifacts-short
  <<:                              *common-refs
  <<:                              *kubernetes-env
  script:
    - npm ci --ignore-scripts
    - npm run build
    - mkdir -p artifacts
    - cp -r build/ artifacts/
    - ls artifacts/

build-docker:
  stage:                           build
  needs:
    - job:                         build-npm
      artifacts:                   true
  <<:                              *test-refs
  <<:                              *kubernetes-env
  <<:                              *build-only-docker-image

#### stage:                        publish

build-push-image:
  stage:                           publish
  needs:
    - job:                         build-npm
      artifacts:                   true
  <<:                              *kubernetes-env
  <<:                              *publish-refs
  image:                           $BUILDAH_IMAGE
  variables:
    DOCKER_USER:                   $Docker_Hub_User_Parity
    DOCKER_PASS:                   $Docker_Hub_Pass_Parity
  script:
    # version is either "master-<short_sha>" or tag
    - if [[ $CI_COMMIT_REF_NAME == "master" ]];
        then
          export VERSION=$CI_COMMIT_REF_NAME-${CI_COMMIT_SHORT_SHA};
        else
          export VERSION=$CI_COMMIT_REF_NAME;
        fi
    - test "$DOCKER_USER" -a "$DOCKER_PASS" ||
        ( echo "no docker credentials provided"; exit 1 )
    - $BUILDAH_COMMAND build
        --format=docker
        --build-arg VCS_REF="${CI_COMMIT_SHA}"
        --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
        --build-arg IMAGE_NAME="${IMAGE_NAME}"
        --tag "$IMAGE_NAME:latest"
        --tag "$IMAGE_NAME:$VERSION"
        --file $DOCKERFILE .
    # The job will success only on the protected branch
    - echo "$DOCKER_PASS" |
        buildah login --username "$DOCKER_USER" --password-stdin docker.io
    - buildah info
    - $BUILDAH_COMMAND push --format=v2s2 "$IMAGE_NAME:latest"
    - $BUILDAH_COMMAND push --format=v2s2 "$IMAGE_NAME:$VERSION"
  after_script:
    - buildah logout --all
