---
accounts:
- address: 5GBoBNFP9TA7nAk82i6SUZJimerbdhxaRgyC2PVcdYQMdb8e
  nickname: wnd-staking-miner
endpoints:
- wss://westend-rpc.polkadot.io
method_subscription:
  type: only
  only:
  - pallet: balances
    method: transfer
  - pallet: electionProvierMultiPhase
    method: "*"
  - pallet: "*"
    method: remark
api_subscription: head
reporters:
  console: {}
  matrix:
    roomId: '#westend_faucet:matrix.org'
    server: "https://matrix.org"
    #userId: "(Optional) can be passed via env.MATRIX_USERID"
    #accessToken: "(Optional) can be passed via env.MATRIX_ACCESSTOKEN"